# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-02 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pictures/')),
                ('pic_name', models.CharField(max_length=30)),
                ('pic_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
