# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-05 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
    ]
