# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_remove_picture_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pics.Category'),
            preserve_default=False,
        ),
    ]
